#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="sistema_arm_paint")]
	public partial class sistemaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttb_pontos(tb_pontos instance);
    partial void Updatetb_pontos(tb_pontos instance);
    partial void Deletetb_pontos(tb_pontos instance);
    partial void Inserttb_palavras(tb_palavras instance);
    partial void Updatetb_palavras(tb_palavras instance);
    partial void Deletetb_palavras(tb_palavras instance);
    #endregion
		
		public sistemaDataContext() : 
				base(global::sistema.DAL.Properties.Settings.Default.sistema_arm_paintConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public sistemaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public sistemaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public sistemaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public sistemaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb_pontos> tb_pontos
		{
			get
			{
				return this.GetTable<tb_pontos>();
			}
		}
		
		public System.Data.Linq.Table<tb_palavras> tb_palavras
		{
			get
			{
				return this.GetTable<tb_palavras>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_pontos")]
	public partial class tb_pontos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nome;
		
		private System.Nullable<int> _pontos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OnpontosChanging(System.Nullable<int> value);
    partial void OnpontosChanged();
    #endregion
		
		public tb_pontos()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="NVarChar(50)")]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pontos", DbType="Int")]
		public System.Nullable<int> pontos
		{
			get
			{
				return this._pontos;
			}
			set
			{
				if ((this._pontos != value))
				{
					this.OnpontosChanging(value);
					this.SendPropertyChanging();
					this._pontos = value;
					this.SendPropertyChanged("pontos");
					this.OnpontosChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_palavras")]
	public partial class tb_palavras : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _palavra1;
		
		private string _palavra2;
		
		private string _palavra3;
		
		private string _palavra4;
		
		private string _palavra5;
		
		private string _palavra6;
		
		private string _palavra7;
		
		private string _palavra8;
		
		private string _palavra9;
		
		private string _palavra10;
		
		private string _palavra11;
		
		private string _palavra12;
		
		private string _palavra13;
		
		private string _palavra14;
		
		private string _palavra15;
		
		private string _palavra16;
		
		private string _palavra17;
		
		private string _palavra18;
		
		private string _palavra19;
		
		private string _palavra20;
		
		private string _traducao1;
		
		private string _traducao2;
		
		private string _traducao3;
		
		private string _traducao4;
		
		private string _traducao5;
		
		private string _traducao6;
		
		private string _traducao7;
		
		private string _traducao8;
		
		private string _traducao9;
		
		private string _traducao10;
		
		private string _traducao11;
		
		private string _traducao12;
		
		private string _traducao13;
		
		private string _traducao14;
		
		private string _traducao15;
		
		private string _traducao16;
		
		private string _traducao17;
		
		private string _traducao18;
		
		private string _traducao19;
		
		private string _traducao20;
		
		private string _resposta;
		
		private System.Nullable<int> _sequencia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onpalavra1Changing(string value);
    partial void Onpalavra1Changed();
    partial void Onpalavra2Changing(string value);
    partial void Onpalavra2Changed();
    partial void Onpalavra3Changing(string value);
    partial void Onpalavra3Changed();
    partial void Onpalavra4Changing(string value);
    partial void Onpalavra4Changed();
    partial void Onpalavra5Changing(string value);
    partial void Onpalavra5Changed();
    partial void Onpalavra6Changing(string value);
    partial void Onpalavra6Changed();
    partial void Onpalavra7Changing(string value);
    partial void Onpalavra7Changed();
    partial void Onpalavra8Changing(string value);
    partial void Onpalavra8Changed();
    partial void Onpalavra9Changing(string value);
    partial void Onpalavra9Changed();
    partial void Onpalavra10Changing(string value);
    partial void Onpalavra10Changed();
    partial void Onpalavra11Changing(string value);
    partial void Onpalavra11Changed();
    partial void Onpalavra12Changing(string value);
    partial void Onpalavra12Changed();
    partial void Onpalavra13Changing(string value);
    partial void Onpalavra13Changed();
    partial void Onpalavra14Changing(string value);
    partial void Onpalavra14Changed();
    partial void Onpalavra15Changing(string value);
    partial void Onpalavra15Changed();
    partial void Onpalavra16Changing(string value);
    partial void Onpalavra16Changed();
    partial void Onpalavra17Changing(string value);
    partial void Onpalavra17Changed();
    partial void Onpalavra18Changing(string value);
    partial void Onpalavra18Changed();
    partial void Onpalavra19Changing(string value);
    partial void Onpalavra19Changed();
    partial void Onpalavra20Changing(string value);
    partial void Onpalavra20Changed();
    partial void Ontraducao1Changing(string value);
    partial void Ontraducao1Changed();
    partial void Ontraducao2Changing(string value);
    partial void Ontraducao2Changed();
    partial void Ontraducao3Changing(string value);
    partial void Ontraducao3Changed();
    partial void Ontraducao4Changing(string value);
    partial void Ontraducao4Changed();
    partial void Ontraducao5Changing(string value);
    partial void Ontraducao5Changed();
    partial void Ontraducao6Changing(string value);
    partial void Ontraducao6Changed();
    partial void Ontraducao7Changing(string value);
    partial void Ontraducao7Changed();
    partial void Ontraducao8Changing(string value);
    partial void Ontraducao8Changed();
    partial void Ontraducao9Changing(string value);
    partial void Ontraducao9Changed();
    partial void Ontraducao10Changing(string value);
    partial void Ontraducao10Changed();
    partial void Ontraducao11Changing(string value);
    partial void Ontraducao11Changed();
    partial void Ontraducao12Changing(string value);
    partial void Ontraducao12Changed();
    partial void Ontraducao13Changing(string value);
    partial void Ontraducao13Changed();
    partial void Ontraducao14Changing(string value);
    partial void Ontraducao14Changed();
    partial void Ontraducao15Changing(string value);
    partial void Ontraducao15Changed();
    partial void Ontraducao16Changing(string value);
    partial void Ontraducao16Changed();
    partial void Ontraducao17Changing(string value);
    partial void Ontraducao17Changed();
    partial void Ontraducao18Changing(string value);
    partial void Ontraducao18Changed();
    partial void Ontraducao19Changing(string value);
    partial void Ontraducao19Changed();
    partial void Ontraducao20Changing(string value);
    partial void Ontraducao20Changed();
    partial void OnrespostaChanging(string value);
    partial void OnrespostaChanged();
    partial void OnsequenciaChanging(System.Nullable<int> value);
    partial void OnsequenciaChanged();
    #endregion
		
		public tb_palavras()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_palavra1", DbType="NVarChar(MAX)")]
		public string palavra1
		{
			get
			{
				return this._palavra1;
			}
			set
			{
				if ((this._palavra1 != value))
				{
					this.Onpalavra1Changing(value);
					this.SendPropertyChanging();
					this._palavra1 = value;
					this.SendPropertyChanged("palavra1");
					this.Onpalavra1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_palavra2", DbType="NVarChar(MAX)")]
		public string palavra2
		{
			get
			{
				return this._palavra2;
			}
			set
			{
				if ((this._palavra2 != value))
				{
					this.Onpalavra2Changing(value);
					this.SendPropertyChanging();
					this._palavra2 = value;
					this.SendPropertyChanged("palavra2");
					this.Onpalavra2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_palavra3", DbType="NVarChar(MAX)")]
		public string palavra3
		{
			get
			{
				return this._palavra3;
			}
			set
			{
				if ((this._palavra3 != value))
				{
					this.Onpalavra3Changing(value);
					this.SendPropertyChanging();
					this._palavra3 = value;
					this.SendPropertyChanged("palavra3");
					this.Onpalavra3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_palavra4", DbType="NVarChar(MAX)")]
		public string palavra4
		{
			get
			{
				return this._palavra4;
			}
			set
			{
				if ((this._palavra4 != value))
				{
					this.Onpalavra4Changing(value);
					this.SendPropertyChanging();
					this._palavra4 = value;
					this.SendPropertyChanged("palavra4");
					this.Onpalavra4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_palavra5", DbType="NVarChar(MAX)")]
		public string palavra5
		{
			get
			{
				return this._palavra5;
			}
			set
			{
				if ((this._palavra5 != value))
				{
					this.Onpalavra5Changing(value);
					this.SendPropertyChanging();
					this._palavra5 = value;
					this.SendPropertyChanged("palavra5");
					this.Onpalavra5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_palavra6", DbType="NVarChar(MAX)")]
		public string palavra6
		{
			get
			{
				return this._palavra6;
			}
			set
			{
				if ((this._palavra6 != value))
				{
					this.Onpalavra6Changing(value);
					this.SendPropertyChanging();
					this._palavra6 = value;
					this.SendPropertyChanged("palavra6");
					this.Onpalavra6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_palavra7", DbType="NVarChar(MAX)")]
		public string palavra7
		{
			get
			{
				return this._palavra7;
			}
			set
			{
				if ((this._palavra7 != value))
				{
					this.Onpalavra7Changing(value);
					this.SendPropertyChanging();
					this._palavra7 = value;
					this.SendPropertyChanged("palavra7");
					this.Onpalavra7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_palavra8", DbType="NVarChar(MAX)")]
		public string palavra8
		{
			get
			{
				return this._palavra8;
			}
			set
			{
				if ((this._palavra8 != value))
				{
					this.Onpalavra8Changing(value);
					this.SendPropertyChanging();
					this._palavra8 = value;
					this.SendPropertyChanged("palavra8");
					this.Onpalavra8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_palavra9", DbType="NVarChar(MAX)")]
		public string palavra9
		{
			get
			{
				return this._palavra9;
			}
			set
			{
				if ((this._palavra9 != value))
				{
					this.Onpalavra9Changing(value);
					this.SendPropertyChanging();
					this._palavra9 = value;
					this.SendPropertyChanged("palavra9");
					this.Onpalavra9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_palavra10", DbType="NVarChar(MAX)")]
		public string palavra10
		{
			get
			{
				return this._palavra10;
			}
			set
			{
				if ((this._palavra10 != value))
				{
					this.Onpalavra10Changing(value);
					this.SendPropertyChanging();
					this._palavra10 = value;
					this.SendPropertyChanged("palavra10");
					this.Onpalavra10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_palavra11", DbType="NVarChar(MAX)")]
		public string palavra11
		{
			get
			{
				return this._palavra11;
			}
			set
			{
				if ((this._palavra11 != value))
				{
					this.Onpalavra11Changing(value);
					this.SendPropertyChanging();
					this._palavra11 = value;
					this.SendPropertyChanged("palavra11");
					this.Onpalavra11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_palavra12", DbType="NVarChar(MAX)")]
		public string palavra12
		{
			get
			{
				return this._palavra12;
			}
			set
			{
				if ((this._palavra12 != value))
				{
					this.Onpalavra12Changing(value);
					this.SendPropertyChanging();
					this._palavra12 = value;
					this.SendPropertyChanged("palavra12");
					this.Onpalavra12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_palavra13", DbType="NVarChar(MAX)")]
		public string palavra13
		{
			get
			{
				return this._palavra13;
			}
			set
			{
				if ((this._palavra13 != value))
				{
					this.Onpalavra13Changing(value);
					this.SendPropertyChanging();
					this._palavra13 = value;
					this.SendPropertyChanged("palavra13");
					this.Onpalavra13Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_palavra14", DbType="NVarChar(MAX)")]
		public string palavra14
		{
			get
			{
				return this._palavra14;
			}
			set
			{
				if ((this._palavra14 != value))
				{
					this.Onpalavra14Changing(value);
					this.SendPropertyChanging();
					this._palavra14 = value;
					this.SendPropertyChanged("palavra14");
					this.Onpalavra14Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_palavra15", DbType="NVarChar(MAX)")]
		public string palavra15
		{
			get
			{
				return this._palavra15;
			}
			set
			{
				if ((this._palavra15 != value))
				{
					this.Onpalavra15Changing(value);
					this.SendPropertyChanging();
					this._palavra15 = value;
					this.SendPropertyChanged("palavra15");
					this.Onpalavra15Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_palavra16", DbType="NVarChar(MAX)")]
		public string palavra16
		{
			get
			{
				return this._palavra16;
			}
			set
			{
				if ((this._palavra16 != value))
				{
					this.Onpalavra16Changing(value);
					this.SendPropertyChanging();
					this._palavra16 = value;
					this.SendPropertyChanged("palavra16");
					this.Onpalavra16Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_palavra17", DbType="NVarChar(MAX)")]
		public string palavra17
		{
			get
			{
				return this._palavra17;
			}
			set
			{
				if ((this._palavra17 != value))
				{
					this.Onpalavra17Changing(value);
					this.SendPropertyChanging();
					this._palavra17 = value;
					this.SendPropertyChanged("palavra17");
					this.Onpalavra17Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_palavra18", DbType="NVarChar(MAX)")]
		public string palavra18
		{
			get
			{
				return this._palavra18;
			}
			set
			{
				if ((this._palavra18 != value))
				{
					this.Onpalavra18Changing(value);
					this.SendPropertyChanging();
					this._palavra18 = value;
					this.SendPropertyChanged("palavra18");
					this.Onpalavra18Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_palavra19", DbType="NVarChar(MAX)")]
		public string palavra19
		{
			get
			{
				return this._palavra19;
			}
			set
			{
				if ((this._palavra19 != value))
				{
					this.Onpalavra19Changing(value);
					this.SendPropertyChanging();
					this._palavra19 = value;
					this.SendPropertyChanged("palavra19");
					this.Onpalavra19Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_palavra20", DbType="NVarChar(MAX)")]
		public string palavra20
		{
			get
			{
				return this._palavra20;
			}
			set
			{
				if ((this._palavra20 != value))
				{
					this.Onpalavra20Changing(value);
					this.SendPropertyChanging();
					this._palavra20 = value;
					this.SendPropertyChanged("palavra20");
					this.Onpalavra20Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_traducao1", DbType="NVarChar(MAX)")]
		public string traducao1
		{
			get
			{
				return this._traducao1;
			}
			set
			{
				if ((this._traducao1 != value))
				{
					this.Ontraducao1Changing(value);
					this.SendPropertyChanging();
					this._traducao1 = value;
					this.SendPropertyChanged("traducao1");
					this.Ontraducao1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_traducao2", DbType="NVarChar(MAX)")]
		public string traducao2
		{
			get
			{
				return this._traducao2;
			}
			set
			{
				if ((this._traducao2 != value))
				{
					this.Ontraducao2Changing(value);
					this.SendPropertyChanging();
					this._traducao2 = value;
					this.SendPropertyChanged("traducao2");
					this.Ontraducao2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_traducao3", DbType="NVarChar(MAX)")]
		public string traducao3
		{
			get
			{
				return this._traducao3;
			}
			set
			{
				if ((this._traducao3 != value))
				{
					this.Ontraducao3Changing(value);
					this.SendPropertyChanging();
					this._traducao3 = value;
					this.SendPropertyChanged("traducao3");
					this.Ontraducao3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_traducao4", DbType="NVarChar(MAX)")]
		public string traducao4
		{
			get
			{
				return this._traducao4;
			}
			set
			{
				if ((this._traducao4 != value))
				{
					this.Ontraducao4Changing(value);
					this.SendPropertyChanging();
					this._traducao4 = value;
					this.SendPropertyChanged("traducao4");
					this.Ontraducao4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_traducao5", DbType="NVarChar(MAX)")]
		public string traducao5
		{
			get
			{
				return this._traducao5;
			}
			set
			{
				if ((this._traducao5 != value))
				{
					this.Ontraducao5Changing(value);
					this.SendPropertyChanging();
					this._traducao5 = value;
					this.SendPropertyChanged("traducao5");
					this.Ontraducao5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_traducao6", DbType="NVarChar(MAX)")]
		public string traducao6
		{
			get
			{
				return this._traducao6;
			}
			set
			{
				if ((this._traducao6 != value))
				{
					this.Ontraducao6Changing(value);
					this.SendPropertyChanging();
					this._traducao6 = value;
					this.SendPropertyChanged("traducao6");
					this.Ontraducao6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_traducao7", DbType="NVarChar(MAX)")]
		public string traducao7
		{
			get
			{
				return this._traducao7;
			}
			set
			{
				if ((this._traducao7 != value))
				{
					this.Ontraducao7Changing(value);
					this.SendPropertyChanging();
					this._traducao7 = value;
					this.SendPropertyChanged("traducao7");
					this.Ontraducao7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_traducao8", DbType="NVarChar(MAX)")]
		public string traducao8
		{
			get
			{
				return this._traducao8;
			}
			set
			{
				if ((this._traducao8 != value))
				{
					this.Ontraducao8Changing(value);
					this.SendPropertyChanging();
					this._traducao8 = value;
					this.SendPropertyChanged("traducao8");
					this.Ontraducao8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_traducao9", DbType="NVarChar(MAX)")]
		public string traducao9
		{
			get
			{
				return this._traducao9;
			}
			set
			{
				if ((this._traducao9 != value))
				{
					this.Ontraducao9Changing(value);
					this.SendPropertyChanging();
					this._traducao9 = value;
					this.SendPropertyChanged("traducao9");
					this.Ontraducao9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_traducao10", DbType="NVarChar(MAX)")]
		public string traducao10
		{
			get
			{
				return this._traducao10;
			}
			set
			{
				if ((this._traducao10 != value))
				{
					this.Ontraducao10Changing(value);
					this.SendPropertyChanging();
					this._traducao10 = value;
					this.SendPropertyChanged("traducao10");
					this.Ontraducao10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_traducao11", DbType="NVarChar(MAX)")]
		public string traducao11
		{
			get
			{
				return this._traducao11;
			}
			set
			{
				if ((this._traducao11 != value))
				{
					this.Ontraducao11Changing(value);
					this.SendPropertyChanging();
					this._traducao11 = value;
					this.SendPropertyChanged("traducao11");
					this.Ontraducao11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_traducao12", DbType="NVarChar(MAX)")]
		public string traducao12
		{
			get
			{
				return this._traducao12;
			}
			set
			{
				if ((this._traducao12 != value))
				{
					this.Ontraducao12Changing(value);
					this.SendPropertyChanging();
					this._traducao12 = value;
					this.SendPropertyChanged("traducao12");
					this.Ontraducao12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_traducao13", DbType="NVarChar(MAX)")]
		public string traducao13
		{
			get
			{
				return this._traducao13;
			}
			set
			{
				if ((this._traducao13 != value))
				{
					this.Ontraducao13Changing(value);
					this.SendPropertyChanging();
					this._traducao13 = value;
					this.SendPropertyChanged("traducao13");
					this.Ontraducao13Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_traducao14", DbType="NVarChar(MAX)")]
		public string traducao14
		{
			get
			{
				return this._traducao14;
			}
			set
			{
				if ((this._traducao14 != value))
				{
					this.Ontraducao14Changing(value);
					this.SendPropertyChanging();
					this._traducao14 = value;
					this.SendPropertyChanged("traducao14");
					this.Ontraducao14Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_traducao15", DbType="NVarChar(MAX)")]
		public string traducao15
		{
			get
			{
				return this._traducao15;
			}
			set
			{
				if ((this._traducao15 != value))
				{
					this.Ontraducao15Changing(value);
					this.SendPropertyChanging();
					this._traducao15 = value;
					this.SendPropertyChanged("traducao15");
					this.Ontraducao15Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_traducao16", DbType="NVarChar(MAX)")]
		public string traducao16
		{
			get
			{
				return this._traducao16;
			}
			set
			{
				if ((this._traducao16 != value))
				{
					this.Ontraducao16Changing(value);
					this.SendPropertyChanging();
					this._traducao16 = value;
					this.SendPropertyChanged("traducao16");
					this.Ontraducao16Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_traducao17", DbType="NVarChar(MAX)")]
		public string traducao17
		{
			get
			{
				return this._traducao17;
			}
			set
			{
				if ((this._traducao17 != value))
				{
					this.Ontraducao17Changing(value);
					this.SendPropertyChanging();
					this._traducao17 = value;
					this.SendPropertyChanged("traducao17");
					this.Ontraducao17Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_traducao18", DbType="NVarChar(MAX)")]
		public string traducao18
		{
			get
			{
				return this._traducao18;
			}
			set
			{
				if ((this._traducao18 != value))
				{
					this.Ontraducao18Changing(value);
					this.SendPropertyChanging();
					this._traducao18 = value;
					this.SendPropertyChanged("traducao18");
					this.Ontraducao18Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_traducao19", DbType="NVarChar(MAX)")]
		public string traducao19
		{
			get
			{
				return this._traducao19;
			}
			set
			{
				if ((this._traducao19 != value))
				{
					this.Ontraducao19Changing(value);
					this.SendPropertyChanging();
					this._traducao19 = value;
					this.SendPropertyChanged("traducao19");
					this.Ontraducao19Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_traducao20", DbType="NVarChar(MAX)")]
		public string traducao20
		{
			get
			{
				return this._traducao20;
			}
			set
			{
				if ((this._traducao20 != value))
				{
					this.Ontraducao20Changing(value);
					this.SendPropertyChanging();
					this._traducao20 = value;
					this.SendPropertyChanged("traducao20");
					this.Ontraducao20Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resposta", DbType="NVarChar(MAX)")]
		public string resposta
		{
			get
			{
				return this._resposta;
			}
			set
			{
				if ((this._resposta != value))
				{
					this.OnrespostaChanging(value);
					this.SendPropertyChanging();
					this._resposta = value;
					this.SendPropertyChanged("resposta");
					this.OnrespostaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sequencia", DbType="Int")]
		public System.Nullable<int> sequencia
		{
			get
			{
				return this._sequencia;
			}
			set
			{
				if ((this._sequencia != value))
				{
					this.OnsequenciaChanging(value);
					this.SendPropertyChanging();
					this._sequencia = value;
					this.SendPropertyChanged("sequencia");
					this.OnsequenciaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
